name: Deploy to Prod ECR

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        
      - name: Configure IRAF AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.IRAF_PROD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.IRAF_PROD_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to IRAF Amazon ECR
        id: login-iraf-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to IRAF Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-iraf-ecr.outputs.registry }}
          ECR_REPOSITORY: prod-trade-react-app
        run: |
          docker build -t prod-trade-react-app --platform=linux/amd64 . -f Prod.Dockerfile
          docker tag prod-trade-react-app:latest $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.run_number }} 
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.run_number }}
      
      - name: Dispatch TTF infastructure
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.DEPLOY_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/TheTokenFoundry/ttf-infrastructure/dispatches \
            -d '{"event_type":"deploy_frontend_image_prod","client_payload":{"run_number":${{ github.run_number }}}}'
